{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyMnP2gfu9G7Gj8Fyh7bbwey"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["#### 에러(Error) vs. 예외(Exception).\n","\n","에러(Error):\n","- 에러는 주로 프로그램 실행 전에 발생하는, 프로그램의 잘못된 구문이나 절차 등에 의해 발생하는 문제를 말한다.\n","- 대표적인 에러로는 구문 에러(SyntaxError)가 있다. 예를 들어, 올바르지 않은 들여쓰기나 잘못된 코드 구조로 인해 파이썬 인터프리터가 코드를 실행하기 전에 에러를 발생시킨다.\n","- 에러는 대체로 프로그램의 수정 없이는 복구될 수 없는 심각한 문제들이다.\n","\n","예외(Exception):\n","- 예외는 실행 중인 프로그램에 영향을 주는 이벤트로, 일반적인 프로그램 흐름을 방해한다.\n","- 예외는 프로그램의 정상적인 흐름을 방해하지만, 적절한 예외 처리를 통해 프로그램의 중단 없이 예외를 '잡아내고(catch)' 처리할 수 있다. 예를 들어, 파일을 열 때 파일이 존재하지 않는 경우 FileNotFoundError 예외가 발생할 수 있다. 이 경우 적절한 except 블록으로 예외를 처리하여 사용자에게 메시지를 표시하고 대안적인 행동을 취할 수 있다.\n","- 예외는 try-except 블록을 통해 프로그램에서 처리할 수 있으며, 이를 통해 프로그램이 예외 상황에서도 안정적으로 동작하도록 만들 수 있다.\n","\n","요약하자면, 에러는 대개 코드 수정이 필요한 문제들을 가리키며, 예외는 프로그램 실행 중에 발생하지만 적절히 처리할 수 있는 예상 가능한 '예외적' 상황들을 말한다.\n","\n","#### 파이썬에서 발생할 수 있는 에러와 예외의 유형:\n","에러 : 프로그램이 실행되기 전에 발생하는 문제\n","- SyntaxError: 코드의 구문이 잘못되었을 때 생긴다.<br>\n","\n","예외 : 실행 시간(runtime) 중에 발생하고 처리 가능\n","- NameError: 정의되지 않은 변수를 호출할 때 생긴다.\n","- TypeError: 연산이나 함수가 부적절한 유형의 객체에 적용될 때 발생한다.\n","- ValueError: 연산이나 함수가 적절하지 않은 값을 객체에 적용할 때 발생한다.\n","- IndexError: 리스트 등의 시퀀스에서 존재하지 않는 인덱스를 사용할 때 생긴다.\n","- KeyError: 딕셔너리에서 존재하지 않는 키를 사용할 때 발생한다.\n","- AttributeError: 존재하지 않는 속성이나 메서드를 호출할 때 생긴다.\n","- IOError 또는 OSError: 파일 입출력 과정에서 에러가 생길 때 발생한다.\n","- ZeroDivisionError: 0으로 나눌 때 생긴다.\n","- ImportError: 모듈을 임포트할 수 없을 때 발생한다.\n","- StopIteration: 이터레이터에 더 이상의 아이템이 없을 때 next()를 호출하면 발생한다.\n","- MemoryError: 메모리 할당이 실패할 때 생긴다.\n","- RecursionError: 재귀 호출이 너무 깊어질 때 발생한다."],"metadata":{"id":"t3f1QbLhFJ9H"}},{"cell_type":"code","source":["# 구문 오류 : 프로그램 실행 전에 발생하는 오류\n","# 예외 또는 런타임 오류 : 프로그램 실행 중 발생하는 오류\n","\n","print('예외를 강제로 발생!)\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":110},"id":"ruw5CazJFLua","executionInfo":{"status":"error","timestamp":1715237306724,"user_tz":-540,"elapsed":337,"user":{"displayName":"sogun lee","userId":"01118584956690988204"}},"outputId":"c41862bf-2222-4d5e-c8df-79db3e699601"},"execution_count":1,"outputs":[{"output_type":"error","ename":"SyntaxError","evalue":"unterminated string literal (detected at line 4) (<ipython-input-1-759f0de067c7>, line 4)","traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-1-759f0de067c7>\"\u001b[0;36m, line \u001b[0;32m4\u001b[0m\n\u001b[0;31m    print('예외를 강제로 발생!)\u001b[0m\n\u001b[0m          ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m unterminated string literal (detected at line 4)\n"]}]},{"cell_type":"code","source":["#SyntaxError : 잘못된 구문\n","for i in range(10)\n","    print(i)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":110},"id":"9kGE9gtkHPgS","executionInfo":{"status":"error","timestamp":1715237386762,"user_tz":-540,"elapsed":3,"user":{"displayName":"sogun lee","userId":"01118584956690988204"}},"outputId":"fb26d6f9-abba-4d7b-a6e2-d3f9738a352a"},"execution_count":2,"outputs":[{"output_type":"error","ename":"SyntaxError","evalue":"expected ':' (<ipython-input-2-5e17f9a34d5e>, line 2)","traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-2-5e17f9a34d5e>\"\u001b[0;36m, line \u001b[0;32m2\u001b[0m\n\u001b[0;31m    for i in range(10)\u001b[0m\n\u001b[0m                      ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m expected ':'\n"]}]},{"cell_type":"code","source":["# NameError : 정의되지 않은 변수 사용\n","print(unknow)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":166},"id":"qfVP8-T9Hkbb","executionInfo":{"status":"error","timestamp":1715237461720,"user_tz":-540,"elapsed":515,"user":{"displayName":"sogun lee","userId":"01118584956690988204"}},"outputId":"7bf23e08-dc1b-4ef2-dc04-9edf9e1a6a88"},"execution_count":3,"outputs":[{"output_type":"error","ename":"NameError","evalue":"name 'unknow' is not defined","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-3-ea6599173d01>\u001b[0m in \u001b[0;36m<cell line: 2>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m# NameError : 정의되지 않은 변수 사용\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0munknow\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mNameError\u001b[0m: name 'unknow' is not defined"]}]}]}